### ISSUE TITLE
HI, I download ,and build . but not anaylz . Why ? code is change?

### ISSUE THREAD

**Issue by yanxuejungit** [zliu1022/Webgo#2]
HI, I download ,and build . but not anaylz . Why ? code is change?

**Comment by yanxuejungit** [comment]
player.analyze.js:282 WebSocket connection to 'ws://localhost:32019/websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by zliu1022** [comment]
Have you launched the server part?
It looks the server's web socket has not created correctly.

yanxuejungit <notifications@github.com> 于2018年11月27日周二 下午2:55写道：

**Comment by zliu1022** [comment]
Compile python as exe on windows platform, please try it again.

1. Download [https://github.com/zliu1022/Webgo/releases/download/v0.1/Webgo.7z](url)
2. Unzip this release and run start.bat.
3. Then open the url in your mobile phone browser.
