### ISSUE TITLE
能否实现不用ssh来远程连接

### ISSUE THREAD

**Issue by ivysrono** [zliu1022/Webgo#3]
家用网络很可能没有公网IP，能否用别的方法实现远程呢？
类似 https://github.com/syncthing/syncthing 这种思路？

**Comment by zliu1022** [comment]
现在就不是SSH,你用过吗

**Comment by ivysrono** [comment]
我用了，局域网内可以直接访问很成功。
我想问的是非局域网环境，能否在没有公网IP，没有服务器的情况下实现访问？
理解可能有偏差，问题没有表述清晰，见谅。
